---
key: dW5pbmp5b1dNamxyRmRBVWxoT2tOY0VK
cacert:
- /home/anvil/anvil/config/certs/0/ca.crt
- /home/anvil/anvil/config/certs/0/server1.crt
- /home/anvil/anvil/config/certs/0/server2.crt
- /home/anvil/anvil/config/certs/0/server3.crt
tlscert: /home/anvil/anvil/config/certs/0/server1.crt
tlskey: /home/anvil/anvil/config/certs/0/server1.key
tokens:
- sname: rotation
  tval: c3hZcnhKVnk2cFpwc1FJV2hMRFpjekpuUldxTnF6MGliY09PZ0YxQ1lGZ0ZvNU93QTNjVVpnS3pWWG5QQWVoOQ==
